name: Main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "8.1"
      - uses: actions/checkout@v2
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Make cache dirs
        run: mkdir -p storage/framework/{sessions,views,cache}
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Generate key
        run: php artisan key:generate
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: vendor/bin/phpunit

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout

        uses: actions/checkout@v2

      - name: Setup Node.js

        uses: actions/setup-node@v2-beta

        with:
          node-version: "12"

          check-latest: true

      - name: Install NPM dependencies

        run: npm install

      - name: Compile assets for production

        run: npm run production

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout

        uses: actions/checkout@v2

      - name: Deployment

        uses: appleboy/ssh-action@master

        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.SSH_USERNAME }}

          script: |
            cd /var/www/jolli_api
            git stash
            git checkout -f main
            git pull -f
            composer install
            cd /var/www/jolli_api/bootstrap/cache
            rm -rf *.php
            cd /var/www/jolli_api
            sudo chmod -R 777 storage bootstrap/cache
            php artisan optimize && php artisan config:clear && php artisan storage:link
            php artisan l5-swagger:generate && php artisan migrate
